# PyTorch로 시작하는 딥러닝 입문
## 1장 : PyTorch의 기초
https://wikidocs.net/book/2788

# Pytorch Tensor Allocation

In [14]:
import torch
import numpy as np

In [3]:
t = torch.FloatTensor([[1., 2., 3.],
                      [4., 5., 6.],
                      [7., 8., 9.]])
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [6]:
print(t.dim())
print(t.size())

2
torch.Size([3, 3])


   ## Broadcasting
   - 크기가 다른 텐서에 대해 사칙 연산을 수행할 필요가 있을 때 자동으로 크기를 맞춰서 연산을 수행하게 만드는 기능

In [7]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [8]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [9]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


[1, 2]
==> [[1, 2],
     [1, 2]]
[3]
[4]
==> [[3, 3],
     [4, 4]]
Broadcasting 단계에서 텐서는 위와 같이 변경된다. 이에 대한 덧셈을 수행하면 위와 같은 결과를 얻을 수 있음을 확인할 수 있다.

## Max & ArgMax
- Max는 원소의 최댓값을 리턴합니다.
- ArgMax는 최대값을 가진 인덱스를 리턴합니다.

In [10]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.max())

tensor(4.)


In [11]:
print(t.max(dim=0)[1]) 
# dim=0인 경우 max와 argmax를 함께 리턴하는 바 [1]로 argmax에 접근할 수 있음

tensor([1, 1])


## View
- 원소의 크기를 유지하면서 텐서의 크기를 변경하는 작업입니다.
- 텐서의 크기 Shape를 변경해주는 역할을 합니다.

In [15]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [16]:
print(ft.shape)

torch.Size([2, 2, 3])


In [17]:
# 3차원 텐서를 2차원 텐서로 변경
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


#### view([-1,3])이 가지는 의미는 다음과 같습니다.
- -1은 첫번째 차원은 사용자가 잘 모르겠으니 pytorch에게 맡긴다는 의미입니다.
- 3은 두번째 차원은 길이가 3이 되도록 하라는 의미입니다.

= view는 기본적으로 변경 전과 변경 후의 tensor 원소 수가 유지되어야 합니다.
= pytorch는 view 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추합니다.

## Squeeze
- 1인 차원을 제거한다는 의미입니다.

## Unsqueeze
- 특정 위치에 1인 차원을 추가한다는 의미입니다.

In [18]:
# squeeze : 3 x 1 to 1차원 벡터
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [19]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [20]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [21]:
# unsqueeze : 1차원 텐서 to (1,3) 2차원 텐서
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [22]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [23]:
print(ft.view(1, -1)) # view로도 같은 연산 수행 가능
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


## Concatenate
- pandas의 concatenation과 동일하게 두 텐서를 연결하는 방법입니다.

In [24]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [25]:
print(torch.cat([x, y], dim=0)) # dim=0일 경우 1차원이 늘어납니다. (2x2)->(4x2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [26]:
print(torch.cat([x, y], dim=1)) # dim=1일 경우 2차원이 늘어납니다. (2x2)->(2x4)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking
- 연결을 하는 또 다른 방법입니다.
- 벡터 여러개를 stack에 순차적으로 쌓아 텐서를 연결합니다.

In [27]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [28]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
